### ISSUE TITLE
How to update to newer kibana?

### ISSUE THREAD

**Issue by HWDexperte** [spinn3r/kibana-4-deb#7]
Aloha,

how is it possible to use this script to get the newest version of kibana to benefit from new features?

**Comment by gboddin** [comment]
This script is meant to create Debian packages of the kibana version mentioned in the pom.xml file.

It's already mentionning the latest version (4.1.2)

You need maven to use it, and then use the follwing command : mvn package

Should you need a pre-build package, feel free to look at my fork of this repo : https://github.com/gboddin/kibana-4-deb/releases

**Comment by burtonator** [comment]
Thanks@gboddin.

Closing this bug.  We're already at the latest version. Just run mvn package.  

gboddin, BTW. If you want I can just give you access to this repo and you can contribute here directly.

**Comment by gboddin** [comment]
@burtonator, sure, as long as Travis allows it that would lower the fork amount :).

**Comment by burtonator** [comment]
OK.  Well either way you have write access now. Definitely a fan of fewer forks.

**Comment by burtonator** [comment]
And hopefully Travis can push artifacts to this repo..
