### ISSUE TITLE
update to 4.3.0

### ISSUE THREAD

**Issue by zabbal** [spinn3r/kibana-4-deb#9]
https://download.elastic.co/kibana/kibana/kibana-4.3.0-linux-x64.tar.gz - sources

**Comment by gboddin** [comment]
Hi, I personaly have to free time to ensure testing for this version before next year ;)

Feel free to fork, try and push-request.

**Comment by zabbal** [comment]
I'd love to but #10 should be resolved first - to make sure that installation fails only because of my changes and not because of some bug upstream.
